version: '3.8'

services:
  db:
    image: postgres:15
    container_name: crypto-db
    environment:
      POSTGRES_DB: crypto          # This should create the "crypto" database
      POSTGRES_USER: postgres       # Superuser for the initial connection
      POSTGRES_PASSWORD: your-postgres-password
    ports:
      - "5432:5432"
    volumes:
      - crypto-db-data:/var/lib/postgresql/data
    networks:
      - crypto-network

volumes:
  crypto-db-data:

networks:
  crypto-network:
    driver: bridge
