version: '3.8'

services:
  db:
    image: postgres:14
    container_name: crypto-db
    environment:
      POSTGRES_DB: crypto
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto@123
    ports:
      - "5432:5432"
    volumes:
      - crypto-db-data:/var/lib/postgresql/data

volumes:
  crypto-db-data: