server:
  port: 8081
  servlet:
    context-path: /crypto

spring:
  flyway:
    enabled: true
    baselineOnMigrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  defaultSchema: crypto

logging:
  level:
    jakarta:
      validation: DEBUG
    org:
      hibernate:
        SQL: DEBUG # Set this to DEBUG to print query in logs
        type: TRACE